// Auto-generated
let project = new Project('vehicle');

project.addSources('Sources');
project.addLibrary("C:/app/Armory/armsdk/armory");
project.addLibrary("C:/app/Armory/armsdk/iron");
project.addLibrary("C:/app/Armory/armsdk/lib/haxebullet");
project.addAssets("C:/app/Armory/armsdk/lib/haxebullet/js/ammo/ammo.js", { notinlist: true });
project.addParameter('armory.trait.internal.CanvasScript');
project.addParameter("--macro keep('armory.trait.internal.CanvasScript')");
project.addParameter('armory.trait.internal.Bridge');
project.addParameter("--macro keep('armory.trait.internal.Bridge')");
project.addParameter('armory.trait.internal.DebugConsole');
project.addParameter("--macro keep('armory.trait.internal.DebugConsole')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('armory.trait.SimpleRotateObject');
project.addParameter("--macro keep('armory.trait.SimpleRotateObject')");
project.addParameter('arm.VehicleBody');
project.addParameter("--macro keep('arm.VehicleBody')");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Blue_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Blue_mesh.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Blue_shadowmap.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Blue_shadowmap.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Blue_voxel.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Blue_voxel.geom.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Blue_voxel.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Material_armskin_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Material_armskin_mesh.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Material_armskin_shadowmap.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Material_armskin_voxel.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Material_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Material_mesh.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Material_shadowmap.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Material_voxel.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Tyre_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Tyre_mesh.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/armdefault_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/backlight_armskin_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/backlight_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/ground_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/road_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/road_side_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/tire_rim_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/tire_rim_mesh.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/wall_concrete_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/wall_metalgate_mesh.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/wall_metalgate_shadowmap.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/wall_metalgate_shadowmap.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/bloom_pass.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/blur_adaptive_pass.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/blur_gaus_pass.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/compositor_pass.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/compositor_pass.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/deferred_indirect.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/deferred_indirect.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/deferred_indirect_VoxelAOvar.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/deferred_indirect_VoxelAOvar.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/deferred_light.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/deferred_light_quad.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/motion_blur_veloc_pass.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/pass.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/pass_copy.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/pass_light_volume.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/pass_viewray.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/pass_viewray2.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/smaa_blend_weight.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/smaa_blend_weight.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/smaa_edge_detect.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/smaa_edge_detect.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/smaa_neighborhood_blend.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/smaa_neighborhood_blend.vert.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/ssgi_blur_pass.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/ssgi_pass.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/ssr_pass.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/taa_pass.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/world_pass.frag.glsl");
project.addShaders("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/world_pass.vert.glsl");
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Blue_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Material_armskin_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Material_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/Tyre_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/armdefault_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/backlight_armskin_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/backlight_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/ground_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/road_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/road_side_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/shader_datas.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/tire_rim_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/wall_concrete_data.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Shaders/wall_metalgate_data.arm", { notinlist: true });
project.addAssets("Assets/checker_rough.png", { notinlist: true });
project.addAssets("Assets/grid.png", { notinlist: true });
project.addAssets("Bundled/Asphalt10_col.jpg", { notinlist: true });
project.addAssets("Bundled/Asphalt10_col_stripe.jpg", { notinlist: true });
project.addAssets("Bundled/Asphalt10_disp.jpg", { notinlist: true });
project.addAssets("Bundled/Asphalt10_mask.jpg", { notinlist: true });
project.addAssets("Bundled/Asphalt10_nrm.jpg", { notinlist: true });
project.addAssets("Bundled/Asphalt10_rgh.jpg", { notinlist: true });
project.addAssets("Bundled/Concrete10_AO.jpg", { notinlist: true });
project.addAssets("Bundled/Concrete10_col.jpg", { notinlist: true });
project.addAssets("Bundled/Concrete10_disp.jpg", { notinlist: true });
project.addAssets("Bundled/Concrete10_nrm.jpg", { notinlist: true });
project.addAssets("Bundled/Concrete10_rgh.jpg", { notinlist: true });
project.addAssets("Bundled/Ground10_AO.jpg", { notinlist: true });
project.addAssets("Bundled/Ground10_col.jpg", { notinlist: true });
project.addAssets("Bundled/Ground10_disp.jpg", { notinlist: true });
project.addAssets("Bundled/Ground10_nrm.jpg", { notinlist: true });
project.addAssets("Bundled/Ground10_rgh.jpg", { notinlist: true });
project.addAssets("Bundled/MetalWalkway04_col.jpg", { notinlist: true });
project.addAssets("Bundled/MetalWalkway04_col.png", { notinlist: true });
project.addAssets("Bundled/MetalWalkway04_disp.jpg", { notinlist: true });
project.addAssets("Bundled/MetalWalkway04_mask.jpg", { notinlist: true });
project.addAssets("Bundled/MetalWalkway04_met.jpg", { notinlist: true });
project.addAssets("Bundled/MetalWalkway04_nrm.jpg", { notinlist: true });
project.addAssets("Bundled/MetalWalkway04_rgh.jpg", { notinlist: true });
project.addAssets("Bundled/canvas/MyCanvas.files", { notinlist: true });
project.addAssets("Bundled/canvas/MyCanvas.json", { notinlist: true });
project.addAssets("Bundled/fire0.wav", { notinlist: true , quality: 0.8999999761581421});
project.addAssets("Bundled/fire1.wav", { notinlist: true , quality: 0.8999999761581421});
project.addAssets("Bundled/luttexture.jpg", { notinlist: true });
project.addAssets("Bundled/step0.wav", { notinlist: true , quality: 0.8999999761581421});
project.addAssets("Bundled/step1.wav", { notinlist: true , quality: 0.8999999761581421});
project.addAssets("C:/app/Armory/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/hosek/hosek_radiance.hdr", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/hosek/hosek_radiance_0.hdr", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/hosek/hosek_radiance_1.hdr", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/hosek/hosek_radiance_2.hdr", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/hosek/hosek_radiance_3.hdr", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/hosek/hosek_radiance_4.hdr", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/hosek/hosek_radiance_5.hdr", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/hosek/hosek_radiance_6.hdr", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/hosek/hosek_radiance_7.hdr", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("C:/app/Armory/armsdk/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/Scene.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/envmaps/World_irradiance.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/action_Armature_idle.aero.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/action_Armature_idle.circuit.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/action_Armature_transform.aero.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/action_Armature_transform.circuit.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.000.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.001.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.002.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.003.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.005.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.011.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.017.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.036.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.042.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.043.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.045.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.061.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.069.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.072.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.073.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.076.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.090.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.096.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.097.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.098.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.099.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cube.100.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cylinder.001.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cylinder.019.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cylinder.020.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cylinder.021.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cylinder.022.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Cylinder.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Plane.003.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Plane.005.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Plane.006.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Plane.1248.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Plane.arm", { notinlist: true });
project.addAssets("C:/Users/chris/armory/armory_templates-18.05b/vehicle/build_vehicle/compiled/Assets/meshes/mesh_Veh.arm", { notinlist: true });
project.addShaders("C:/app/Armory/armsdk//armory/Shaders/debug_draw/**");
project.addLibrary("C:/app/Armory/armsdk/lib/zui");
project.addAssets("C:/app/Armory/armsdk/armory/Assets/droid_sans.ttf", { notinlist: false });
project.addDefine('arm_hosek');
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('arm_voxelgi');
project.addDefine('arm_voxelgi_revox');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_depthprepass');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_size=1024');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=TAA');
project.addDefine('arm_veloc');
project.addDefine('arm_taa');
project.addDefine('rp_supersampling=1.5');
project.addDefine('rp_gi=Voxel AO');
project.addDefine('rp_voxelgi_resolution=128');
project.addDefine('rp_voxelgi_resolution_z=0.5');
project.addDefine('rp_ssgi=RTAO');
project.addDefine('rp_decals');
project.addDefine('rp_bloom');
project.addDefine('rp_ssr');
project.addDefine('rp_motionblur=Object');
project.addDefine('rp_gbuffer2');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_shaderload');
project.addDefine('arm_soundcompress');
project.addDefine('arm_debug');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_particles_gpu');
project.addDefine('arm_particles');
project.addDefine('arm_fast');


resolve(project);
